### ISSUE TITLE
Fix remaining xfail tests in test_accept_batch

### ISSUE THREAD

**Issue by walkerh** [Submissions/shepherd#5]
I added a bunch of a failing tests. All are broken because of needed changes to accept_batch.py.

Additionally, some have mistakes due to trivial things like missing quotes: https://github.com/Submissions/shepherd/blob/8f88eafcff698eacb02a6476cbc04ca9fbf9f1a8/tests/test_accept_batch.py#L67

Work together to get it all passing.

**Comment by cssanchez23** [comment]
This was fixed by Walker and Mahitha on Feb, 20 2018.
