### ISSUE TITLE
Manual test resources for accept_batch now lack the necessary directory structure

### ISSUE THREAD

**Issue by walkerh** [Submissions/shepherd#6]
The directory `tests/resources/accept_batch_manual_test` should have the a structure more like this:

    README.md
    topmed
      phase3
        biome
          01
            24a
              BioMe_batch24a_mplx.tsv
              meta.yaml

This is because accept_batch:

* take a directory path as input
* uses the last 5 components of the path as well as the contents of the directory

Restructure and make sure the manual test works correctly.

**Comment by cssanchez23** [comment]
Fixed this issue.
